# Builds models.js, the list shown under Custom in Settings, from the public OpenRouter model list.
# Usage: curl -s https://openrouter.ai/api/v1/models > models.json
#        python3 scripts/build-models.py models.json models.js
import datetime
import json
import sys

data = json.load(open(sys.argv[1], encoding="utf-8"))["data"]
rows = sorted(
    # Batch endpoints are not meant for chat. Free models get a tag in the list, so "(free)" in the name would repeat it.
    ({"id": m["id"], "name": m["name"].removesuffix(" (free)"), "free": m["id"].endswith(":free")}
     for m in data if not m["id"].endswith(":batch")),
    key=lambda r: r["name"].lower(),
)
out = (
    "// Generated by scripts/build-models.py from the OpenRouter model list, "
    + datetime.date.today().isoformat() + ". Do not edit by hand.\n"
    + "window.ALL_MODELS = [\n"
    + ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in rows)
    + "\n];\n"
)
with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as f:
    f.write(out)
print(len(rows), "models written")
